### ISSUE TITLE
Cannot find module 'ibm-watson/auth'

### ISSUE THREAD

**Issue by alessandrofaraotti** [watson-developer-cloud/node-sdk#1077]
**Overview**
Error afert updating to ibm-watson v5.7.2 in package.json.
Cannot find module 'ibm-watson/auth'

**Expected behavior**
Module is loaded

**Actual behavior**
Error at startup

**How to reproduce**
package.json  add dependency: "ibm-watson" : "5.7.2"

add in any .js (e.g app.js)
const { IamAuthenticator } = require('ibm-watson/auth');

**Screenshots**
Error: Cannot find module 'ibm-watson/auth'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (<myfile.js>:2:30)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**SDK Version**
5.7.2

**Additional information:**
- OS: Window10 / IBM Cloud
- Which version of `Node` are you using? node: v10.16.0

**Comment by dpopp07** [comment]
@apaparazzi0329 we need to look at this ASAP

**Comment by dpopp07** [comment]
Yes, 5.7.2 is broken and unusable. Any package that relies on this with `^` syntax will automatically update and be broken. I am going to publish a fix in 5.7.3 immediately

**Comment by dpopp07** [comment]
5.7.3 is published and should be working again. Thanks for reporting this so quickly. Please let us know if you run into any more issues
