### ISSUE TITLE
Impossible to install ibm-watson - node-gyp-build MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by FrancescoDiMaggio** [watson-developer-cloud/node-sdk#1086]
```
Francesco@DESKTOP~/Documents/2021/app (main)
$ node -v
v14.16.0

Francesco@DESKTOP~/Documents/2021/app (main)
$ npm -v
6.14.11

Francesco@DESKTOP~/Documents/2021/app (main)
$ npm install --save ibm-watson

> bufferutil@4.0.3 install C:\Users\Francesco\Documents\2021\app\node_modules\bufferutil
> node-gyp-build

"CILAG\2021\app\node_modules\.bin\" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'C:\Users\Francesco\Documents\node-gyp-build\bin.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bufferutil@4.0.3 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@4.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Francesco\AppData\Roaming\npm-cache\_logs\2021-03-09T09_40_52_408Z-debug.log
```
Any idea?

**Comment by repjarms** [comment]
@FrancescoDiMaggio thanks for posting this! It looks like you are on Windows, do you have `node-gyp` set up on your machine? It looks like the specific error states that the install process is looking for `node-gyp` at `C:\Users\Francesco\Documents\node-gyp-build\bin.js` and unable to find it.

I'm not a Windows user myself, but I did find this StackOverflow post where some folks were discussing this issue on Windows, and it looks like here is an accepted answer that could be promising: https://stackoverflow.com/questions/50420537/node-gyp-installation-failures-on-windows

Let me know if this helps, or seems like it's on the right track for your issue.
