### ISSUE TITLE
Assistant timezone

### ISSUE THREAD

**Issue by allyssonf** [watson-developer-cloud/node-sdk#1101]
---

**Overview**
When trying to set Assistant timezone for proper behavior when sending message an UnhandledPromiseRejectionWarning is thrown for every message exchanged. 

**Expected behavior**
No promises rejection .

**Actual behavior**
```
(node:25264) UnhandledPromiseRejectionWarning: Error: Missing required parameters: assistantId, sessionId
    at Object.getMissingParams (/Users/allysson/Development/Projects/IBM/tl-watson-chat/node_modules/ibm-watson/node_modules/ibm-cloud-sdk-core/lib/helper.js:116:11)
    at AssistantV2.message (/Users/allysson/Development/Projects/IBM/tl-watson-chat/node_modules/ibm-watson/assistant/v2.js:209:50)
    at /Users/allysson/Development/Projects/IBM/tl-watson-chat/server.js:103:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**How to reproduce**
Just try to send a message with following parameters:
```
    const param = {
      input: { text: message || '' },
      assistantId: process.env.WA_ID || '',
      sessionId: sessionId,
      context: {
        global: {
          system: {
            timezone: 'America/Sao_Paulo'
          }
        }
      }
    };
``` 

**SDK Version**
^6.1.1

**Additional information:**
- OS: MacOS Big Sur 11.04 
- Which version of `Node` are you using? 12.6.1

**Additional context**
There is no clear information on docs (at least that I found) that points how to properly set timezone on Assistant.

**Comment by allyssonf** [comment]
Sorry, this was a typo in my code.
