### ISSUE TITLE
Error: Cannot find module 'tough-cookie'

### ISSUE THREAD

**Issue by oshihirii** [watson-developer-cloud/node-sdk#1116]
Node: 14.18.1  
OS: windows 10  
ibm-watson:  "^6.2.1"  
@babel/cli: "^7.16.0"  
@babel/core: "^7.16.0"  
@babel/preset-env: "^7.16.0"  

I have recently upgraded to node `14.18.1` and from ibm-watson `4.2.2` to `6.2.1`.  

When I try and run the app, I get the errors below:  

```
$ npm run start

> showcase@1.0.0 start D:\REPOS\my application
> node app.js

internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'tough-cookie'
Require stack:
- D:\REPOS\my application\node_modules\axios-cookiejar-support\lib\interceptors\request.js
- D:\REPOS\my application\node_modules\axios-cookiejar-support\lib\index.js
- D:\REPOS\my application\node_modules\ibm-cloud-sdk-core\lib\request-wrapper.js
- D:\REPOS\my application\node_modules\ibm-cloud-sdk-core\auth\token-managers\token-manager.js
- D:\REPOS\my application\node_modules\ibm-cloud-sdk-core\auth\token-managers\jwt-token-manager.js
- D:\REPOS\my application\node_modules\ibm-cloud-sdk-core\auth\token-managers\iam-request-based-token-manager.js
- D:\REPOS\my application\node_modules\ibm-cloud-sdk-core\auth\token-managers\iam-token-manager.js
- D:\REPOS\my application\node_modules\ibm-cloud-sdk-core\auth\token-managers\index.js
- D:\REPOS\my application\node_modules\ibm-cloud-sdk-core\auth\authenticators\cloud-pak-for-data-authenticator.js
- D:\REPOS\my application\node_modules\ibm-cloud-sdk-core\auth\authenticators\index.js
- D:\REPOS\my application\node_modules\ibm-cloud-sdk-core\auth\index.js
- D:\REPOS\my application\node_modules\ibm-cloud-sdk-core\lib\base-service.js
- D:\REPOS\my application\node_modules\ibm-cloud-sdk-core\index.js
- D:\REPOS\my application\node_modules\ibm-watson\lib\synthesize-stream.js
- D:\REPOS\my application\node_modules\ibm-watson\text-to-speech\v1.js
- D:\REPOS\my application\app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (D:\REPOS\my application\node_modules\axios-cookiejar-support\lib\interceptors\request.js:8:4
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\REPOS\\my application\\node_modules\\axios-cookiejar-support\\lib\\interceptors\\request.js',
    'D:\\REPOS\\my application\\node_modules\\axios-cookiejar-support\\lib\\index.js',
    'D:\\REPOS\\my application\\node_modules\\ibm-cloud-sdk-core\\lib\\request-wrapper.js',
    'D:\\REPOS\\my application\\node_modules\\ibm-cloud-sdk-core\\auth\\token-managers\\token-manager.js',
    'D:\\REPOS\\my application\\node_modules\\ibm-cloud-sdk-core\\auth\\token-managers\\jwt-token-manager.js',
    'D:\\REPOS\\my application\\node_modules\\ibm-cloud-sdk-core\\auth\\token-managers\\iam-request-based-token-manager
    'D:\\REPOS\\my application\\node_modules\\ibm-cloud-sdk-core\\auth\\token-managers\\iam-token-manager.js',
    'D:\\REPOS\\my application\\node_modules\\ibm-cloud-sdk-core\\auth\\token-managers\\index.js',
    'D:\\REPOS\\my application\\node_modules\\ibm-cloud-sdk-core\\auth\\authenticators\\cloud-pak-for-data-authenticato
    'D:\\REPOS\\my application\\node_modules\\ibm-cloud-sdk-core\\auth\\authenticators\\index.js',
    'D:\\REPOS\\my application\\node_modules\\ibm-cloud-sdk-core\\auth\\index.js',
    'D:\\REPOS\\my application\\node_modules\\ibm-cloud-sdk-core\\lib\\base-service.js',
    'D:\\REPOS\\my application\\node_modules\\ibm-cloud-sdk-core\\index.js',
    'D:\\REPOS\\my application\\node_modules\\ibm-watson\\lib\\synthesize-stream.js',
    'D:\\REPOS\\my application\\node_modules\\ibm-watson\\text-to-speech\\v1.js',
    'D:\\REPOS\\my application\\app.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! showcase@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the showcase@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Me\AppData\Roaming\npm-cache\_logs\2021-11-01T05_06_28_318Z-debug.log
```

In case it is related:

I import into my server side file with:

    var TextToSpeechV1 = require('ibm-watson/text-to-speech/v1');

I can see the file exists at:

    D:\REPOS\my application\node_modules\ibm-watson\text-to-speech\v1.js  

I run babel on my server side file with this command:  

   babel app_es6.js --out-file app.js

My `.babelrc.json` file contains this:

```
{
  "presets": ["@babel/preset-env"]
}
```

**Comment by oshihirii** [comment]
I had to run:

    npm uninstall ibm-watson

then:

    npm install ibm-watson

And that error went away.  

I'm not sure why.

I got the idea from [this post](https://stackoverflow.com/a/36639811), not sure if it is relevant though.
