### ISSUE TITLE
Handle null parameter fields gracefully

### ISSUE THREAD

**Issue by jpbufe3** [watson-developer-cloud/node-sdk#118]
If a null parameter is supplied to a method, an error will be thrown rather than returned through the callback.

Example:
```
.../watson-developer-cloud/node_modules/request/request.js:340
      if (value.hasOwnProperty('value') && value.hasOwnProperty('options')) {
               ^
TypeError: Cannot read property 'hasOwnProperty' of null
    at appendFormValue (.../watson-developer-cloud/node_modules/request/request.js:340:16)
    at Request.init (.../watson-developer-cloud/node_modules/request/request.js:354:11)
    at new Request (.../watson-developer-cloud/node_modules/request/request.js:140:8)
    at request (.../watson-developer-cloud/node_modules/request/index.js:55:10)
    at createRequest (.../watson-developer-cloud/lib/requestwrapper.js:129:10)
    at Dialog.createDialog (.../watson-developer-cloud/services/dialog/v1.js:188:10)
```

**Comment by germanattanasio** [comment]
Hi @jpbufe3, can you provide the code you are using ?

**Comment by jpbufe3** [comment]
example code with credentials redacted:
```
var watson = require('watson-developer-cloud');
var credentials = { ... }; // insert credentials here
var dialog = watson.dialog(credentials);

var xml = ''; // insert xml from http://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/dialog/download/Exercise_1_end.xml here

// convert string to stream from - http://stackoverflow.com/questions/12755997/how-to-create-streams-from-string-in-node-js
var s = new stream.Readable();
s._read = function noop() {};
s.push(xml);
s.push(null);

var params = {
  name: 'name',
  file: s,
  id: null
};

dialog.createDialog(params, function handleResults (err, results) {
  // handle results
});
```

The first problem is that this code will result in the error stack provided in the original comment. Additionally, if you remove the "id: null" line then it will result in the following error (this may be user error, but unsure why the stream provided wouldn't work):

```
{
  "code":400,
  "error":"Unable to read incoming parameters. - org.apache.commons.fileupload.FileUploadBase$IOFileUploadException: Processing of multipart/form-data request failed. Stream ended unexpectedly"
}
```

**Comment by jancurin** [comment]
The problem was in the way how the stream for reading the XML file was created.
With the previous code, the multipart body in the POST request was invalid (truncated because the length of the XML input loaded via stream was ignored).

This is the code which works for me:

```javascript
var watson = require('watson-developer-cloud');
var fs     = require('fs');

// Insert url of the Watson Dialog service and your credentials here
var credentials = {
  url: 'https://gateway.watsonplatform.net/dialog/api',
  username: '<your credentials>',
  password: '<your password>',
  version: 'v1'
};
var dialog = watson.dialog(credentials);

// Specify name of dialog (it should be unique), read XML stream from file (on your local file system)
// Sample XML file can be downloaded for example from https://github.com/watson-developer-cloud/movieapp-dialog/blob/master/src/main/resources/dialog_files/movieapp-dialog-file.xml
var params = {
  name: 'movieapp',
  file: fs.createReadStream('./movieapp-dialog-file.xml')
};

dialog.createDialog(params, function handleResults (err, results) {
  // handle results
  console.log('error:', err);
  console.log('results:', results);
});
```

The result (returned value) should be something like:

```javascript
results: { dialog_id: '79f8404e-957d-4c8e-a756-259febfa6fe1' }
```

**Comment by germanattanasio** [comment]
Thanks for the clarification @jancurin, I'm gonna close this.

**Comment by jpbufe3** [comment]
@germanattanasio: Jan's solution addressed the second part, but not the first.

There is still an open problem where the requestfactory does not cleanse or gracefully handle null parameters, which will crash the call.

**Comment by germanattanasio** [comment]
ups.

**Comment by germanattanasio** [comment]
I fixed this here, but this is a problem in the request library so I've open an issue there too. https://github.com/request/request/issues/1832
