### ISSUE TITLE
Watson Assistant Session can't be created, because the resource is not found.

### ISSUE THREAD

**Issue by thomassuedbroecker** [watson-developer-cloud/node-sdk#1180]
## **1. Service Status**

* Watson Assistant | 3 Active locations OK

## **2. Overview**
_What is the issue? Be concise and clear._

Watson Assistant Session can't be created, because the resource is not found.
I followed the steps in the [IBM Cloud documentation create session](https://cloud.ibm.com/apidocs/assistant/assistant-v2?code=node#createsession)

GitHub project to verify:  https://github.com/thomassuedbroecker/verify-node-js-watson-assistant

## **3. Expected behavior**
_What did you expect to happen?_

I would like to get the `session ID`.

## **4. Actual behavior**
_What actually happened?_

```sh
Not Found: Resource not found
    at RequestWrapper.formatError (/Users/.../dev/watson-assistant-oidc-nodejs/simple-app/node_modules/ibm-cloud-sdk-core/lib/request-wrapper.js:299:21)
    at /Users/.../dev/watson-assistant-oidc-nodejs/simple-app/node_modules/ibm-cloud-sdk-core/lib/request-wrapper.js:284:45
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  statusText: 'Not Found',
  status: 404,
  code: 404,
  body: '{"error":"Resource not found","code":404}',
  headers: {
    'access-control-allow-origin': '*',
    'access-control-allow-methods': 'GET, POST, PUT, DELETE, PATCH, HEAD, OPTIONS',
    'access-control-allow-headers': 'Content-Type, Content-Length, Authorization, X-Watson-Authorization-Token, X-WDC-PL-OPT-OUT, X-Watson-UserInfo, X-Watson-Learning-Opt-Out, X-Watson-Metadata',
    'access-control-max-age': '3600',
    'content-security-policy': "default-src 'none'",
    'x-dns-prefetch-control': 'off',
    'x-frame-options': 'SAMEORIGIN',
    'strict-transport-security': 'max-age=15552000; includeSubDomains, max-age=31536000; includeSubDomains;',
    'x-download-options': 'noopen',
    'x-content-type-options': 'nosniff',
    'x-xss-protection': '1; mode=block',
    'content-type': 'application/json; charset=utf-8',
    'content-length': '41',
    'x-dp-watson-tran-id': 'a43f3785-dfc7-4885-a883-4c8b2a1608d6',
    'x-request-id': 'a43f3785-dfc7-4885-a883-4c8b2a1608d6',
    'x-global-transaction-id': 'a43f3785-dfc7-4885-a883-4c8b2a1608d6',
    server: 'watson-gateway',
    'x-edgeconnect-midmile-rtt': '98',
    'x-edgeconnect-origin-mex-latency': '41',
    date: 'Tue, 06 Dec 2022 14:24:50 GMT',
    connection: 'close'
  }
}
```

## **5. How to reproduce**

* Follow the step in the exmaple GitHub project to verify:  https://github.com/thomassuedbroecker/verify-node-js-watson-assistant

## **6. SDK Version**

* "ibm-watson": "^7.1.2"

## **7. Additional information:**

* Mac OS:  Version 12.6
* npm -version 8.19.3
* node --version v19.0.1

**Comment by thomassuedbroecker** [comment]
Problem is solved see code https://github.com/thomassuedbroecker/verify-node-js-watson-assistant/blob/main/code/simple-app/server.js#L37.

Wrong information environment ID is needed not assistant ID.
