### ISSUE TITLE
SDK does not work when run through webpack

### ISSUE THREAD

**Issue by bradennapier** [watson-developer-cloud/node-sdk#283]
This service is unbelievably hard to get started with.  Your links aren't working, when you add a credit card you can't get back to console without searching on google or knowing the link, services are difficult and confusing to navigate...

Now to the actual problem... I created a service and got a JSON for credentials taht does NOT include any kind of version.  There is zero indication of "version" anywhere on any documentation for your TTS service anywhere.  You ahve NOTHING in any docs indicating how to get this version information... so I use the example since it is TTS and use v1...

I have checked the login and password on my bluemix console 10,000 times - and yet I get an error the second I call 

```
watson.authorization({
     username: '<my username>',
    password: '<my password>',
    version: 'v1'
})
```

`
Service authorization v1 not found.`

**Comment by nfriedly** [comment]
Hi @bradennapier,

I'm sorry to hear you're having so much trouble.

> Your links aren't working,

Can you point me to which specific links aren't working?

> ` Service authorization v1 not found.`

Are you you trying to use the code via browserify/webpack/etc? The current version of the Node.js SDK only works in Node.js, however client-side support has been frequently requested, and I've been [working on it](https://github.com/watson-developer-cloud/node-sdk/tree/browser) for the past week or so. (It's not ready yet, though.)

For Text to Speech in Web Browsers, please use the [watson-speech](https://www.npmjs.com/package/watson-speech) package for the moment - it's browserify friendly and has [lots of examples](https://github.com/watson-developer-cloud/speech-javascript-sdk/tree/master/examples/static/), including a [node.js server](https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/master/examples/server.js) to run the Authorization service and generate access tokens. (The authorization service must be used on the server rather than on the client, otherwise it'll leak your credentials, which defeats it's main purpose.)

Again, I'm sorry for all of the trouble. A lot of this stuff is really new and I know there's lots of room for improvement. Myself and many others are working very hard to get it there. Please give this a shot, and if it doesn't resolve your issues, let me know what your goal is and where you're getting stuck.

**Comment by bradennapier** [comment]
Well I am using that as well but the node sdk's authorization does not work server side.  I am running it via Node 4.3 on Amazon Lambda AWS and get that error every time.

Serivde authorization v1 not found occurs the second I call

``` watson.authorization({ ...authData }) ```

i changed to using the request package and a simple HTTP get and it works... not a good experience

**Comment by bradennapier** [comment]
```
import watson from 'watson-developer-cloud'
const auth = watson.authorization({
     version: 'v1',
     username: 'username here',
     password: 'pw here',
   })
```

**Comment by nfriedly** [comment]
Hum, I haven't tried that. I wonder if lambda (or perhaps babel?) does something similar to browserify where it drops files that aren't explicitly require()'d. 

If you have a minute, could you test it with node-sdk from the `browser` branch? It's not ready for browsers, but there's a chance that it would work better on Lambda. Although if request is working for you, and you don't want to take the time, I totally understand.

I think this is the right command will do the trick to install the branch:

    npm install --save "https://github.com/watson-developer-cloud/node-sdk#browser"

**Comment by bradennapier** [comment]
It did not like that at all :-P

``` 

WARNING in ../~/websocket/lib/BufferUtil.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../build/default/bufferutil in /home/ubuntu/workspace/node_modules/websocket/lib
 @ ../~/websocket/lib/BufferUtil.js 11:19-57

WARNING in ../~/websocket/lib/Validation.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../build/default/validation in /home/ubuntu/workspace/node_modules/websocket/lib
 @ ../~/websocket/lib/Validation.js 11:21-59

WARNING in ../~/websocket/build/Release/bufferutil.node
Module parse failed: /home/ubuntu/workspace/node_modules/websocket/build/Release/bufferutil.node Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '' (1:0)
    at Parser.pp.raise (/home/ubuntu/workspace/node_modules/acorn/dist/acorn.js:923:13)
    at Parser.pp.getTokenFromCode (/home/ubuntu/workspace/node_modules/acorn/dist/acorn.js:2831:8)
    at Parser.pp.readToken (/home/ubuntu/workspace/node_modules/acorn/dist/acorn.js:2526:15)
    at Parser.pp.nextToken (/home/ubuntu/workspace/node_modules/acorn/dist/acorn.js:2518:71)
    at Parser.parse (/home/ubuntu/workspace/node_modules/acorn/dist/acorn.js:1631:10)
    at Object.parse (/home/ubuntu/workspace/node_modules/acorn/dist/acorn.js:885:44)
    at Parser.parse (/home/ubuntu/workspace/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/home/ubuntu/workspace/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/home/ubuntu/workspace/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/home/ubuntu/workspace/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /home/ubuntu/workspace/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/home/ubuntu/workspace/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /home/ubuntu/workspace/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
 @ ../~/websocket/lib/BufferUtil.js 9:19-57

WARNING in ../~/websocket/build/Release/validation.node
Module parse failed: /home/ubuntu/workspace/node_modules/websocket/build/Release/validation.node Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '' (1:0)
    at Parser.pp.raise (/home/ubuntu/workspace/node_modules/acorn/dist/acorn.js:923:13)
    at Parser.pp.getTokenFromCode (/home/ubuntu/workspace/node_modules/acorn/dist/acorn.js:2831:8)
    at Parser.pp.readToken (/home/ubuntu/workspace/node_modules/acorn/dist/acorn.js:2526:15)
    at Parser.pp.nextToken (/home/ubuntu/workspace/node_modules/acorn/dist/acorn.js:2518:71)
    at Parser.parse (/home/ubuntu/workspace/node_modules/acorn/dist/acorn.js:1631:10)
    at Object.parse (/home/ubuntu/workspace/node_modules/acorn/dist/acorn.js:885:44)
    at Parser.parse (/home/ubuntu/workspace/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/home/ubuntu/workspace/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/home/ubuntu/workspace/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/home/ubuntu/workspace/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /home/ubuntu/workspace/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/home/ubuntu/workspace/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /home/ubuntu/workspace/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
 @ ../~/websocket/lib/Validation.js 9:21-59
```

**Comment by nfriedly** [comment]
>_< 

Well, thanks for trying. I guess I'll have to say stick with request for now. 

From that stack trace it looks like webpack is involved in there somehow - can I ask what your setup looks like to bundle up the code and send it to Lambda?

Also, I'm about out of time for tonight and have a pretty busy weekend ahead, so you might not hear back from me until next week.

**Comment by nfriedly** [comment]
Hey, I just setup a Webpack 2 example that can fully load the SDK. It's targeted at a browser, so you may need a few tweaks to run it on lambda, but it should be a good starting point:

https://github.com/watson-developer-cloud/node-sdk/tree/master/examples/webpack

**Comment by germanattanasio** [comment]
Nice work @nfriedly!
