### ISSUE TITLE
[conversation]error message incorrect when version_date is undefined

### ISSUE THREAD

**Issue by Mikemosca** [watson-developer-cloud/node-sdk#306]
in v1.js the following code seems to have the wrong value of version_date.  Should it be **2016-07-11**?

  if (typeof this._options.version_date === 'undefined') {
    throw new Error('Argument error: version_date was not specified, use 2016-07-01');
  }

**Comment by Mikemosca** [comment]
you guys are fast!

**Comment by vkg70** [comment]
I'm still getting this error.

var NaturalLanguageUnderstandingV1 = require('watson-developer-cloud/natural-language-understanding/v1.js');

var nlu = new NaturalLanguageUnderstandingV1({
  username: process.env.NLU_USERNAME,
  password: process.env.NLU_PASSWORD,
  version_date: NaturalLanguageUnderstandingV1.VERSION_DATE_2017_02_27
});

/Users/vijaygupta/Documents/GitHub/TestGitHub/TFS/node_modules/watson-developer-cloud/natural-language-understanding/v1.js:31
    throw new Error('Argument error: version_date was not specified, use NaturalLanguageUnderstandingV1.VERSION_DATE_2016_01_23');
    ^

Error: Argument error: version_date was not specified, use NaturalLanguageUnderstandingV1.VERSION_DATE_2016_01_23
    at new NaturalLanguageUnderstandingV1 (/Users/xxxxxxx/Documents/GitHub/TestGitHub/TFS/node_modules/watson-developer-cloud/natural-language-understanding/v1.js:31:11)
    at Object.<anonymous> (/Users/xxxxxxx/Documents/GitHub/TestGitHub/xxx/app.js:39:11)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
