### ISSUE TITLE
[speech-to-text] async is not declared in package.json dependencies

### ISSUE THREAD

**Issue by l2fprod** [watson-developer-cloud/node-sdk#330]
I have an app that was using version "*" for the watson-developer-cloud in its package.json.

It just picked up version 2.7.0 and fails when deployed to Bluemix with:

```
2016-10-26T08:23:04.59+0000 [App/0]      ERR     throw err;
2016-10-26T08:23:04.59+0000 [App/0]      ERR     ^
2016-10-26T08:23:04.59+0000 [App/0]      ERR Error: Cannot find module 'async'
2016-10-26T08:23:04.59+0000 [App/0]      ERR     at Function.Module._resolveFilename (module.js:326:15)
2016-10-26T08:23:04.59+0000 [App/0]      ERR     at Function.Module._load (module.js:277:25)
2016-10-26T08:23:04.59+0000 [App/0]      ERR     at Module.require (module.js:354:17)
2016-10-26T08:23:04.59+0000 [App/0]      ERR     at require (internal/module.js:12:17)
2016-10-26T08:23:04.59+0000 [App/0]      ERR     at Object.<anonymous> (/home/vcap/app/node_modules/watson-developer-cloud/speech-to-text/v1.js:32:13)
2016-10-26T08:23:04.59+0000 [App/0]      ERR     at Module._compile (module.js:410:26)
2016-10-26T08:23:04.59+0000 [App/0]      ERR     at Object.Module._extensions..js (module.js:417:10)
2016-10-26T08:23:04.59+0000 [App/0]      ERR     at Module.load (module.js:344:32)
2016-10-26T08:23:04.59+0000 [App/0]      ERR     at Function.Module._load (module.js:301:12)
2016-10-26T08:23:04.59+0000 [App/0]      ERR     at Module.require (module.js:354:17)
2016-10-26T08:23:04.59+0000 [App/0]      ERR     at require (internal/module.js:12:17)
2016-10-26T08:23:04.59+0000 [App/0]      ERR     at Object.<anonymous> (/home/vcap/app/node_modules/watson-developer-cloud/index.js:45:26)
2016-10-26T08:23:04.59+0000 [App/0]      ERR     at Module._compile (module.js:410:26)
2016-10-26T08:23:04.59+0000 [App/0]      ERR     at Module.load (module.js:344:32)
2016-10-26T08:23:04.59+0000 [App/0]      ERR     at Function.Module._load (module.js:301:12)
2016-10-26T08:23:04.62+0000 [App/0]      ERR npm ERR! Linux 3.19.0-33-generic
2016-10-26T08:23:04.62+0000 [App/0]      ERR npm ERR! argv "/home/vcap/app/vendor/node/bin/node" "/home/vcap/app/vendor/node/bin/npm" "start"
```

async seems to be missing from dependencies in package.json. It is in devDependencies but given devDependencies are not installed on Bluemix unless you set NPM_CONFIG_PRODUCTION to false it leads to an error.

2.6.2 did not have this problem.

Here is a sample app to reproduce the issue:

[watsonbug.zip](https://github.com/watson-developer-cloud/node-sdk/files/552838/watsonbug.zip)

**Comment by nfriedly** [comment]
Oh, shoot. Sorry about that. `v2.7.1` should be out with the fix shortly.

**Comment by nfriedly** [comment]
BTW, I just added https://www.npmjs.com/package/dependency-lint to the tests and confirmed that it would have caught this issue, so it shouldn't happen again.
