### ISSUE TITLE
speech to text token

### ISSUE THREAD

**Issue by xinyi1989** [watson-developer-cloud/node-sdk#600]
i update the watson modules from 2.41.1 to 3.0.1, then got the speech to text token service error,
get token code is 
var authorization = new watson.AuthorizationV1({
        username: stt_credentials.username || '',
        password: stt_credentials.password || '',
        url: stt_credentials.url || watson.SpeechToTextV1.URL
    });
    authorization.getToken(function (err, token) {
        if (!token) {
            console.log('error:', err);
        } else {
           return cb(null,token);
        }
    });
the credentials is right, and the error is below,
 error: { Error: Forbidden
    at Request._callback (C:\personal\project\liguang\ricoh-service\node_modules\watson-developer-cloud\lib\requestwrapper.js:99:21)
    at Request.self.callback (C:\personal\project\liguang\ricoh-service\node_modules\watson-developer-cloud\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\personal\project\liguang\ricoh-service\node_modules\watson-developer-cloud\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Gunzip.<anonymous> (C:\personal\project\liguang\ricoh-service\node_modules\watson-developer-cloud\node_modules\request\request.js:1085:12)
    at Gunzip.g (events.js:291:16)
    at emitNone (events.js:91:20)
  code: 403,
  error: 'Forbidden',
  description: '2017-12-18T01:48:25-06:00, Error ERCD-NOCONFIG occurred when accessing https://127.0.0.1/speech-to-text/api/watson-auth-token?Client-IP=106.38.0.106;Client-CN=;, Tran-Id: gateway02-739270281 - ',
  'x-global-transaction-id': 'ffea405d5a3772c91082aa13' }

is there some change when the modules update?

**Comment by xinyi1989** [comment]
i solve the problem
