### ISSUE TITLE
I keep getting this error 401:not authorised [natural langauge understanding]

### ISSUE THREAD

**Issue by devshiva619** [watson-developer-cloud/node-sdk#617]
node version - 8.9.4

I used this as the reference and copied the exact same code: https://www.ibm.com/watson/developercloud/natural-language-understanding/api/v1/?node#post-analyze

And replaced the username and password with my generated credentials.

#### Everything works fine with the same credentials in python code supplied here : https://www.ibm.com/watson/developercloud/natural-language-understanding/api/v1/?python#post-analyze

When I am trying to authenticate with my generated credentials for natural language understanding I keep getting this error.

```
error: { Error: Not Authorized
    at Request._callback (/home/dexter/node_modules/watson-developer-cloud/lib/requestwrapper.js:99:21)
    at Request.self.callback (/home/dexter/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/dexter/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/dexter/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
  code: 401,
  error: 'Not Authorized',
  description: '2018-01-27T05:13:15-06:00, Error ERCDPLTFRM-INVLDCHR occurred when accessing https://gateway.watsonplatform.net/natural-language-understanding/api/v1/analyze?version=2017-02-27, Tran-Id: gateway02-981308249 - ',
  'x-global-transaction-id': undefined }
```

**Comment by anweshan** [comment]
Are you still getting this error? I tried the example with the latest version (3.0.5) of the node-sdk and I do not get this error.

**Comment by anweshan** [comment]
If you are running the code in browser, see https://github.com/watson-developer-cloud/node-sdk/issues/618 - you may be getting an unauthorized error because CORS is not enabled currently for NLU

**Comment by devshiva619** [comment]
@anweshan it started working, I dont know what I did 😄
