### ISSUE TITLE
[visual-recognition] Issue in identifying class

### ISSUE THREAD

**Issue by dibeesh** [watson-developer-cloud/node-sdk#756]
While trying to classify an image the below error is showing

```
{ Error: {"images":[{"source_url":"http://img.wbcsrv.com/2018/07/25/6583987383-1279-918129745148-1532502783000.jpg","resolved_url":"http://img.wbcsrv.com/2018/07/25/6583987383-1279-918129745148-1532502783000.jpg","error":{"code":400,"description":"Did not find any valid classifier_ids specified in the request. owners parameter was null, tried to find these ids: [DefaultCustomModel_415001599]"}}],"images_processed":1}
7/25/2018 12:43:10 PM    at Request._callback (/src/node_modules/watson-developer-cloud/lib/requestwrapper.js:113:21)
7/25/2018 12:43:10 PM    at Request.self.callback (/src/node_modules/request/request.js:185:22)
7/25/2018 12:43:10 PM    at emitTwo (events.js:126:13)
7/25/2018 12:43:10 PM    at Request.emit (events.js:214:7)
7/25/2018 12:43:10 PM    at Request.<anonymous> (/src/node_modules/request/request.js:1157:10)
7/25/2018 12:43:10 PM    at emitOne (events.js:116:13)
7/25/2018 12:43:10 PM    at Request.emit (events.js:211:7)
7/25/2018 12:43:10 PM    at IncomingMessage.<anonymous> (/src/node_modules/request/request.js:1079:12)
7/25/2018 12:43:10 PM    at Object.onceWrapper (events.js:313:30)
7/25/2018 12:43:10 PM    at emitNone (events.js:111:20)
7/25/2018 12:43:10 PM    at IncomingMessage.emit (events.js:208:7)
7/25/2018 12:43:10 PM    at endReadableNT (_stream_readable.js:1064:12)
7/25/2018 12:43:10 PM    at _combinedTickCallback (internal/process/next_tick.js:138:11)
7/25/2018 12:43:10 PM    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
7/25/2018 12:43:10 PM  code: 400,
7/25/2018 12:43:10 PM  'x-global-transaction-id': 'c0b54f935b58230508a74a14' }
```
But this is not consistent. Sometimes it is working.

**Comment by dpopp07** [comment]
Hi @dibeesh 

Interesting. This sounds like it may be a problem with the service. Will you please post the code you are using to make the request?

**Comment by dibeesh** [comment]
Thankyou for looking into the issue. Below is the codethat we are using

VisualRecognitionV3 = require('watson-developer-cloud/visual-recognition/v3')
var visualRecognition = new VisualRecognitionV3({
				api_key: config.api.VR_APIKEY,
				version: '2017-05-26'
			});
		
			var params = {
				url: http://img.wbcsrv.com/2018/07/25/6583987383-1279-918129745148-1532502783000.jpg,
				classifier_ids:'DefaultCustomModel_415001599',
				threshold: 0.7
			};
			visualRecognition.classify(params, function (err, res) {
				if (err) {
					console.log(err);
					reject(err);
				} else {
					console.log(JSON.stringify(res));
					resolve(res);
				}
			});

**Comment by germanattanasio** [comment]
@dibeesh Make sure when you list the classifiers with `listClassifiers()` your classifier id matches the one from the service. I would also try using a different `version` and finally, you should switch to use the new `iam_api_key`. Create a new service instance and train your classifier again.

**Comment by dpopp07** [comment]
Hi @dibeesh, did the above suggestions work for you? If not, please let me know and I will open an issue against the service

**Comment by dpopp07** [comment]
Closing this issue due to inactivity. If this problem persists, please comment again and we will re-open.
