### ISSUE TITLE
[AssistantV1] _options is not defined error when createDialogNode

### ISSUE THREAD

**Issue by karikalanarun** [watson-developer-cloud/node-sdk#805]
[ ] Steps to reproduce

```
const Assistant = require("watson-developer-cloud/assistant/v1")
let assistant = credentials => (new Assistant({
    version: '2018-09-20',
    username: credentials.username,
    password: credentials.password,
    url: 'https://gateway.watsonplatform.net/conversation/api'
}));
```

```
const simpleDialog = {
    workspace_id: <my_workspace_id>,
    dialog_node: "node_1",
    title: "summa"
}

assistant(<credentials>).createDialogNode(simpleDialog)
```

[ ] Expected behavior
   I think the above code is valid thing. it will create an dialog node.

[ ] Actual behavior
```
TypeError: Cannot read property '_options' of undefined
    at AssistantV1.createDialogNode (/Users/Arun/official/repo/cogni-bot-api/node_modules/watson-developer-cloud/assistant/v1.js:2156:51)
    at internal/util.js:281:30
    at /Users/Arun/official/repo/cogni-bot-api/index.js:14:48
    at Object.<anonymous> (/Users/Arun/official/repo/cogni-bot-api/dialog.example.js:27:19)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
```

Node version - v10.7.0
SDK version - 3.13.0

**Comment by dpopp07** [comment]
Hi @karikalanarun 
Good question - this took me a minute to figure out. The Node SDK, like many libraries, relies on the `this` variable. Turns out, `util.promisify` does not bind the context of `this` so it becomes `undefined`

The workaround for this is to define another variable on the original `assistant` object so that the context is kept. For Example:

```
const util = require('util');
const Assistant = require("watson-developer-cloud/assistant/v1")
const credentials = <>;
const assistant = new Assistant({
    version: '2018-09-20',
    username: credentials.username,
    password: credentials.password,
    url: 'https://gateway.watsonplatform.net/conversation/api'
});

const simpleDialog = {
    workspace_id: <my_workspace_id>,
    dialog_node: "node_1",
    title: "summa"
}

assistant.createDialogNodePromisified = util.promisify(assistant.createDialogNode);

assistant.createDialogNodePromisified(simpleDialog)
  .then(res => {
    console.log(res);
  })
  .catch(err => {
    console.log(err);
  })
```

**Comment by karikalanarun** [comment]
Ohh thank you very much @dpopp07
