### ISSUE TITLE
Internal Server Error - ibm-cloud-sdk-core/lib/requestwrapper.js

### ISSUE THREAD

**Issue by gi-joe-moto** [watson-developer-cloud/node-sdk#923]
I checked that status is it reports that it's ok.  This could be an intermittent issue, however the requestwrapper .js should have error handling for these types of issues IMHO.

**Overview**

We call Watson Assistant several thousand times a day... most of the time it works... sometimes it give an error.

   ```
2019-07-30T13:16:37.66-0500 [APP/PROC/WEB/0] ERR { message: [32m'Server Error'[39m,
   2019-07-30T13:16:37.66-0500 [APP/PROC/WEB/0] ERR   stack:
   2019-07-30T13:16:37.66-0500 [APP/PROC/WEB/0] ERR    [32m'Internal Server Error: Server Error\n    at formatError (/home/vcap/app/node_modules/ibm-watson/node_modules/ibm-cloud-sdk-core/lib/requestwrapper.js:111:17)\n    at /home/vcap/app/node_modules/ibm-watson/node_modules/ibm-cloud-sdk-core/lib/requestwrapper.js:259:19\n    at process._tickCallback (internal/process/next_tick.js:68:7)'[39m,
   2019-07-30T13:16:37.66-0500 [APP/PROC/WEB/0] ERR   name: [32m'Internal Server Error'[39m,
   2019-07-30T13:16:37.66-0500 [APP/PROC/WEB/0] ERR   code: [33m500[39m,
   2019-07-30T13:16:37.66-0500 [APP/PROC/WEB/0] ERR   body:
   2019-07-30T13:16:37.66-0500 [APP/PROC/WEB/0] ERR    [32m'{"code":500,"error":"Server Error","description":"2019-07-30T13:16:37-05:00, Error occurred when accessing https://gateway.watsonplatform.net/assistant/api/v2/assistants/<my-assistant-id>/sessions?version=2018-11-08, Tran-Id: gateway01-1309897221 - Watson Gateway Error"}'[39m,
   2019-07-30T13:16:37.66-0500 [APP/PROC/WEB/0] ERR   headers:
   2019-07-30T13:16:37.66-0500 [APP/PROC/WEB/0] ERR    { [32m'x-dp-watson-tran-id'[39m: [32m'gateway01-1309897221'[39m,
   2019-07-30T13:16:37.66-0500 [APP/PROC/WEB/0] ERR      [32m'content-type'[39m: [32m'application/json'[39m,
   2019-07-30T13:16:37.66-0500 [APP/PROC/WEB/0] ERR      [32m'x-backside-transport'[39m: [32m'FAIL FAIL'[39m,
   2019-07-30T13:16:37.66-0500 [APP/PROC/WEB/0] ERR      [32m'content-length'[39m: [32m'303'[39m,
   2019-07-30T13:16:37.66-0500 [APP/PROC/WEB/0] ERR      [32m'x-edgeconnect-midmile-rtt'[39m: [32m'19'[39m,
   2019-07-30T13:16:37.66-0500 [APP/PROC/WEB/0] ERR      [32m'x-edgeconnect-origin-mex-latency'[39m: [32m'62'[39m,
   2019-07-30T13:16:37.66-0500 [APP/PROC/WEB/0] ERR      date: [32m'Tue, 30 Jul 2019 18:16:37 GMT'[39m,
   2019-07-30T13:16:37.66-0500 [APP/PROC/WEB/0] ERR      connection: [32m'close'[39m } }
```
**Expected behavior**
I expected Watson Assistant to respond with a status code 200 and results.

**Actual behavior**
See error message above for actual response.

**How to reproduce**
Our ask module. 
``` javascript
const AssistantV2 = require('ibm-watson/assistant/v2');
const ASSISTANT_ID = process.env.WA_ASSISTANT_ID;

let WA;

const getWA = () => {
  if (!WA) {
    WA = new AssistantV2({
      version: '2018-11-08',
      iam_apikey: process.env.WA_API_KEY,
      url: 'https://gateway.watsonplatform.net/assistant/api', // default
      headers: {
        'X-Watson-Learning-Opt-Out': 'true'
      }
    });
  }

  return WA;
};

const createSession = async (options) => {
  const WA = getWA();
  return WA.createSession({
    assistant_id: options.assistant_id
  });
};

const deleteSession = async (options) => {
  const WA = getWA();
  return WA.deleteSession({
    assistant_id: options.assistant_id,
    session_id: options.session_id
  });
};

const message = async (options) => {
  const WA = getWA();
  return WA.message({
    assistant_id: options.assistant_id,
    session_id: options.session_id,
    input: options.input,
    context: options.context
  });
};

const ask = async (textInput, uniqueUserID, assistantID) => {
  /**
   * https://cloud.ibm.com/apidocs/assistant-v2?language=node
   *
   * @type {String} textInput - Text to analyze
   * 
   * @type {String} uniqueUserID - A string value that identifies the user who is interacting with the assistant. 
   * The client must provide a unique identifier for each individual end user who accesses the application. 
   * For Plus and Premium plans, this user ID is used to identify unique users for billing purposes. 
   * This string cannot contain carriage return, newline, or tab characters. 
   * THIS VALUE CAN BE NULL
   * 
   * @type {String} assistantID - (Optional) if assistant ID param is passed then it
   * will be used for the analysis or else defaults to the assistant ID configured in the env variable.
   *
   * @return {Object} - JSON Object returned by WA
   */
  
  const assistant_id = assistantID || ASSISTANT_ID;
  let context;
  if (uniqueUserID && uniqueUserID.length >= 1 && uniqueUserID.length <= 256) {
    context = {
      'global':{
        'system':{
          'user_id': uniqueUserID
        }
      }
    };
  } else {
    context = null;
  }

  const session = await createSession({assistant_id});
  const {session_id} = session;
  const result = await message({
    assistant_id,
    session_id,
    input: {
      'text': textInput,
      'options': {
        'return_context': true
      }
    },
    context
  });
  await deleteSession({assistant_id, session_id});
  return result;
};


module.exports = {
  ask
};
```

**SDK Version**
"ibm-watson": "^4.1.1"

**Additional information:**
Windows 10 with WSL
NodeJS v 10.15.3

**Comment by dpopp07** [comment]
@gi-joe-moto Hi, thanks for the issue. Since these are internal service errors, there's nothing we can do about them in the SDK. They are intermittent as you said.

The request wrapper _does_ have error handling for these but you need to incorporate it into your client code. When the service returns an error, the Promise is rejected. Since you are using `async/await`, you can wrap your SDK calls in `try/catch` blocks to handle the errors from the service.

For example:
```js
try {
  const session = await createSession({assistant_id});
} catch(err) {
  console.log('there was an error while creating the session');
  return;
}

const {session_id} = session;
const result = await message({
  assistant_id,
  session_id,
  input: {
    'text': textInput,
    'options': {
      'return_context': true
    }
  },
  context
});
await deleteSession({assistant_id, session_id});
return result;
```

This is a trivial example but that is how you should handle the errors. Does that answer your question?

I think the proper thing to do here from an SDK perspective is to automatically retry the request. This feature is in our backlog but we haven't started work on it yet. Hopefully handling the error this way will work for you in the meantime.

**Comment by gi-joe-moto** [comment]
Gotcha.  I didn't realize until you wrapped the createSession call that it was the one that failed.  Sure enough though `https://gateway.watsonplatform.net/assistant/api/v2/assistants/<my-assistant-id>/sessions?version=2018-11-08`. Interesting... I like your idea of simply retrying the call. 

I'll build that in to see if it reduces our overall failure rate.  Thanks for your response

**Comment by dpopp07** [comment]
No problem!

**Comment by gi-joe-moto** [comment]
So when I retry them they still fail... is there any way to find out why they are failing?  Is there something I'm doing wrong when creating the session?

**Comment by dpopp07** [comment]
If the error has a 500-level status code, that means it is an internal error to the service and there is nothing wrong with the request. Unfortunately, there's nothing you can do about this short of opening a support ticket with the service. How often are you experiencing these errors?

**Comment by gi-joe-moto** [comment]
A few hundred times a day usually...  I will raise it up as an issue with our account owner so they can file a support ticket with the IBM Cloud team.  Thanks for the advise.
