### ISSUE TITLE
Jest cannot parse Typescript files when running `npm test`

### ISSUE THREAD

**Issue by DamianCummins** [watson-developer-cloud/node-sdk#926]
**Overview**
Running `npm test` fails due to Jest failing to parse .ts files.

**Expected behavior**
I expected running `npm install -d && npm test` to succeed as per the [contribution guidelines](https://github.com/watson-developer-cloud/node-sdk/blob/master/.github/CONTRIBUTING.md)

**Actual behavior**
The result of running `npm install -d && npm test` was:
```
Test Suites: 28 failed, 28 total
Tests:       0 total
Snapshots:   0 total
Time:        2.659s
```

An example of one of the test failures is:
```
 FAIL  test/unit/assistant.v1.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    SyntaxError: /Users/dcummin3@uk.ibm.com/workspace/node-sdk/assistant/v1.ts: Unexpected token (28:12)

      26 | class AssistantV1 extends BaseService {
      27 | 
    > 28 |   static URL: string = 'https://gateway.watsonplatform.net/assistant/api';
         |             ^
      29 |   name: string; // set by prototype to 'conversation'
      30 |   serviceVersion: string; // set by prototype to 'v1'
      31 | 

      at Parser.raise (node_modules/@babel/parser/lib/index.js:6344:17)
      at Parser.unexpected (node_modules/@babel/parser/lib/index.js:7659:16)
      at Parser.parseClassMemberWithIsStatic (node_modules/@babel/parser/lib/index.js:10735:12)
      at Parser.parseClassMember (node_modules/@babel/parser/lib/index.js:10631:10)
      at withTopicForbiddingContext (node_modules/@babel/parser/lib/index.js:10586:14)
      at Parser.withTopicForbiddingContext (node_modules/@babel/parser/lib/index.js:9683:14)
      at Parser.parseClassBody (node_modules/@babel/parser/lib/index.js:10563:10)
      at Parser.parseClass (node_modules/@babel/parser/lib/index.js:10537:22)
      at Parser.parseStatementContent (node_modules/@babel/parser/lib/index.js:9830:21)
      at Parser.parseStatement (node_modules/@babel/parser/lib/index.js:9788:17)
```

**How to reproduce**
1. Fork https://github.com/watson-developer-cloud/node-sdk
2. Clone forked repo
3. cd into cloned directory
4. Run `npm install -d && npm test`

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**SDK Version**
https://github.com/DamianCummins/node-sdk - master branch, forked 05/08/19

**Additional information:**
- OS: macOS 10.14.6
- npm --version: 5.6.0
- node --version: v10.0.0
- npm list jest:
ibm-watson@4.3.0 /Users/dcummin3@uk.ibm.com/workspace/node-sdk
└── jest@24.8.0 

**Additional context**
Able to recreate on separate machine running similar setup to above.

**Comment by DamianCummins** [comment]
Running `npm run build` first did the trick. Will close this.

**Comment by dpopp07** [comment]
@DamianCummins looks like the contributions guidelines are out of date. Thanks for bringing this up, I will fix those today
