### ISSUE TITLE
Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

### ISSUE THREAD

**Issue by aximobile** [watson-developer-cloud/node-sdk#929]
**Overview**
Error message 'Block-scoped declarations (let, const, function, class) not yet supported outside strict mode' occurs when deploying a NodeJS web application to IBM cloud

_What is the issue? Be concise and clear._
We use the Cloud foundry CLI to push our application to IBM cloud through the 'cf push <APPNAME>' command.
After building the project, the deployement process automatically tries to start the application but fails to do so. Instead, we receive the following error message:

`2019-08-07T16:15:06.49+0200 [APP/PROC/WEB/0]ERR       let value = keyValueArr[2] || ''
2019-08-07T16:15:06.49+0200 [APP/PROC/WEB/0]ERR       ^^^
2019-08-07T16:15:06.49+0200 [APP/PROC/WEB/0]ERR SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
2019-08-07T16:15:06.49+0200 [APP/PROC/WEB/0]ERR     at exports.runInThisContext (vm.js:53:16)
2019-08-07T16:15:06.49+0200 [APP/PROC/WEB/0]ERR     at Module._compile (module.js:373:25)
2019-08-07T16:15:06.49+0200 [APP/PROC/WEB/0]ERR     at Object.Module._extensions..js (module.js:416:10)
2019-08-07T16:15:06.49+0200 [APP/PROC/WEB/0]ERR     at Module.load (module.js:343:32)
2019-08-07T16:15:06.49+0200 [APP/PROC/WEB/0]ERR     at Function.Module._load (module.js:300:12)
2019-08-07T16:15:06.49+0200 [APP/PROC/WEB/0]ERR     at Module.require (module.js:353:17)
2019-08-07T16:15:06.49+0200 [APP/PROC/WEB/0]ERR     at require (internal/module.js:12:17)
2019-08-07T16:15:06.49+0200 [APP/PROC/WEB/0]ERR     at Object.<anonymous> (/home/vcap/app/node_modules/ibm-watson/node_modules/ibm-cloud-sdk-core/lib/read-credentials-file.js:3:14)
2019-08-07T16:15:06.49+0200 [APP/PROC/WEB/0]ERR     at Module._compile (module.js:409:26)
2019-08-07T16:15:06.49+0200 [APP/PROC/WEB/0]ERR     at Object.Module._extensions..js (module.js:416:10)`

**Expected behavior**
_What did you expect to happen?_
A successful deployment of our web application.

**Actual behavior**
_What actually happened?_
An error message was thrown during the deployment process. 
The logging shows that the error has something to do with the IBM cloud NodeJs BUILDPACK and the ibm-watson package.

**How to reproduce**
_Help us to reproduce what you experienced. Include your code snippets (without credentials)_

1. Create a new NodeJS web project(we used https://github.com/IBM/nodejs-web-app as basis) and include the ibm-watson npm package.
2. Push the web application to IBM cloud with the 'cf push' command.
3. The error message shown above should occur

**SDK Version**
IBM SDK for Node.js Buildpack v3.28-20190722-1336

**Additional information:**
- OS: Linux
- Node version: 4.8.7
- npm version: 2.15.11

**Additional context**
We are receiving the error message since IBM changed from cflinuxfs2 stack to cflinuxfs3 stack as operating system. See https://www.ibm.com/cloud/blog/ibm-cloud-foundry-public-now-supports-cflinuxfs3 for details. **The new stack uses the latest Node BUILDPACK which is causing errors.**

**Comment by dpopp07** [comment]
> We are receiving the error message since IBM changed from cflinuxfs2 stack to cflinuxfs3 stack as operating system.

@aximobile This sounds like an issue with the system or the app repository more than the SDK... Have you opened up an issue against that repo?
