### ISSUE TITLE
Watson Assistant V2 don't work on CP4d 2.1.0.0

### ISSUE THREAD

**Issue by ethilesen** [watson-developer-cloud/node-sdk#933]
Hi,

I'm trying to use V2 to generate a session and it fails with node 10,11 and 12 :(

V1 works just fine...
```
const AssistantV2 = require('ibm-watson/assistant/v2');

const service = new AssistantV2({
  version: '2019-02-28',
  username: 'admin',
  password: 'xxxx',
  icp4d_url: 'https://xxxx:31843',
  authentication_type: 'icp4d',
  url: 'https://xxxx:31843/assistant/my170wa/instances/1565281467/api',
  disable_ssl_verification: true
});

service.createSession({
  assistant_id: 'e7d027d5-d770-4565-b3f3-b08dc32eeae4'
})
  .then(res => {
    console.log(JSON.stringify(res, null, 2));
  })
  .catch(err => {
    console.log(err);
  });

```
```
Error:{ Internal Server Error: Error occurred while creating session
    at RequestWrapper.formatError (/Users/espenthilesen/Developer/node_modules/ibm-watson/node_modules/ibm-cloud-sdk-core/lib/requestwrapper.js:218:21)
    at /Users/espenthilesen/Developer/node_modules/ibm-watson/node_modules/ibm-cloud-sdk-core/lib/requestwrapper.js:206:29
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'Internal Server Error',
  code: 500,
  message: 'Error occurred while creating session',
  body:
   '{"error":"Error occurred while creating session","code":500}',
  headers:
   { server: 'openresty',
     date: 'Mon, 12 Aug 2019 11:43:53 GMT',
     'content-type': 'application/json; charset=utf-8',
     'content-length': '60',
     connection: 'close',
     'access-control-allow-origin': '*',
     'access-control-allow-methods': 'GET, POST, PUT, DELETE, PATCH, HEAD, OPTIONS',
     'access-control-allow-headers':
      'Content-Type, Content-Length, Authorization, X-Watson-Authorization-Token, X-WDC-PL-OPT-OUT, X-Watson-UserInfo, X-Watson-Learning-Opt-Out, X-Watson-Metadata',
     'access-control-max-age': '3600',
     'content-security-policy': 'default-src \'none\'',
     'x-dns-prefetch-control': 'off',
     'x-frame-options': 'SAMEORIGIN',
     'strict-transport-security': 'max-age=15552000; includeSubDomains',
     'x-download-options': 'noopen',
     'x-content-type-options': 'nosniff',
     'x-xss-protection': '1; mode=block',
     vary: 'Accept-Encoding' } }
```

**Comment by dpopp07** [comment]
Hmm looks like a service error, not sure there's anything we can do in the SDK to fix. @germanattanasio do you know why there might have been an error while creating the session?

**Comment by germanattanasio** [comment]
V2 is not supported in CPD
