### ISSUE TITLE
Getting error in at DiscoveryV1.BaseService.initCredentials

### ISSUE THREAD

**Issue by chinmay90kulkarni** [watson-developer-cloud/node-sdk#947]
This error I got when I try to use ibm-watson npm package, version - ^4.4.0 

Error: Insufficient credentials provided in constructor argument. Refer to the documentation for the required parameters. Common examples are username
/password and iam_apikey.
    at DiscoveryV1.BaseService.initCredentials (/app/node_modules/ibm-cloud-sdk-core/lib/base_service.js:307:23)
    at DiscoveryV1.BaseService (/app/node_modules/ibm-cloud-sdk-core/lib/base_service.js:113:29)
    at new DiscoveryV1 (/app/node_modules/ibm-watson/discovery/v1.js:66:28)
    at Object.<anonymous> (/app/node_modules/jdp_bsearch_common/services/discovery.js:18:19)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)

Details of my code . 
const DiscoveryV1 = require('ibm-watson/discovery/v1');

/* Credentials defined in JSON format.*/
const credentials = {"":""}

const discovery = new DiscoveryV1({
    version: '2019-04-02',
    iam_apikey: credentials.apikey,
    url: credentials.url
});

discovery.query(params, (error, results) => {
            if (error) {
                logger.log("queryDiscovery", "Error in discovery " + JSON.stringify(error), "error", true);
                reject(error);
            } else {
                logger.log("queryDiscovery", "Successfully got the query result", "info", true);
                resolve(results)
            }
});

**Comment by dpopp07** [comment]
@chinmay90kulkarni That is really strange, because your code looks fine. That error will be thrown if the `iam_apikey` parameter evaluates to "falsy". Is there a chance that `credentials.apikey` could be `undefined` or an empty string?
